sapcc/openstack-nannies

scripts/vcenter-cleanup.py

We want to keep DRS enabled and set it to "partiallyAutomated". Since
we've already added some overrides, we have to handle the case, where
the override already exists and has a different value.
Additionally, this commit fixes the usage of `ReconfigureCluster_Task`
which is deprecated since 2.5. One should use `ConfigSpecEx` and
`ReconfigureComputeResource_Task` instead.

Update vCenter big VM overrides

---

scripts/cinder-consistency.py

Hi Thomas,
I've taken the liberty to suggest some changes to cinder-consistency.py as we had to find an error in there (as commited by Dmitry) and there was room for improvements in readability.
There's also one error fixed here, so if you don't like the change, please cherry-pick the last commit of the PR.

Some cleanups for cinder-consistency.py

---

scripts/vcenter_consistency_module.py

to keep it in sync with https://github.com/sapcc/openstack-nannies/commit/49ade7014eff435d16ab334c526313c0ca77e596#diff-c8303c86b025bf29b8064fbd5b35a2a9

use 0/1 instead of boolean for mysql

---

nannies/helper/prometheus_connect.py
nannies/vm_load_balance.py

this module is added to pull out metrics from our prometheus_collector @thgrs

added prometheus connect module

---

nannies/requirements.txt

fix requirements.txt

---

nannies/helper/prometheus_connect.py

[vm_balance]: adjusted proper prometheus cert/key file location

---

nannies/vm_load_balance.py

[vm_balance]: bug fix in target_host list

---

nannies/vm_load_balance.py

[nannies]: small_vm calculation not consider for free host finding

---

nannies/helper/prometheus_connect.py
nannies/vm_load_balance.py

[vm_balance_nannies]: monitor vm_readiness and host_contention metrics

---

nannies/vm_load_balance.py

[vm_nannies]: bug fix for success run

---

nannies/vm_load_balance.py

[vm_balance]: bug fix for proper big_uuid in suggestion

---

nannies/vm_load_balance.py

[vm_balance]: added prom metrics when we dont find any large vm for vmotion

---

nannies/helper/prometheus_connect.py

[vm_bal]: more logging for metrics and correction in vm_active_write memory value 

---

nannies/vm_load_balance.py

[vm-balance]: Nannies started monitoring vmotion states

---

nannies/vm_load_balance.py

removed orphaned lines

---

nannies/vm_load_balance.py

[nannies]: vm_balance nannies small bug fix

---

nannies/vm_load_balance.py

[nannies]: fix bug

---

nannies/vm_load_balance.py

[nannies]: fix typo

---

nannies/vm_load_balance.py

This PR includes
- No functional change
- added log message for number of received/checked vm migrations when using migration recommender service

[nannies] add log message with number of received/checked VM migrations

---

nannies/vm_load_balance.py

This PR includes
- No functional change
- added log message for each recommended migration

[nannies] Nannies log message for each migration

---

scripts/manila-share-snapshot.py
scripts/manila-share-snapshot.sh
scripts/manila-share-sync.py
scripts/manila-share-sync.sh
scripts/manilananny.py

3 commits
1- consider replica
2- stuck shares
3- stuck snapshots

manila - handle shares and snapshots in stuck state

---

.gitignore
Dockerfile.manila-nanny
Makefile
k8s/configmap-netapp-filers.yaml
k8s/manila-nanny-snapshot.yaml
nannies/helper/manilananny.py
nannies/helper/prometheus_exporter.py
nannies/manila-missing-snapshot.py
nannies/manila-missing-snapshot.sh
skaffold.yaml

* Add the new nanny file to the nannies/ directory, so that the netapp helper can be conveniently used.
* Add skaffold.yaml and k8s/*.yaml for development setup https://github.com/sapcc/openstack-nannies/pull/56/commits/c04a3fc7b579c26290ca694c216abb3055b47996

manila nanny: find missing snapshots that are not created on Netapp

---

scripts/manila-share-sync.py

- _query_shares() will consider all of its share_instances (i.e. both active and non-active instances/replicas)
- if 'updated_at' field is None, 'created_at' will be considered as last updated time to determine whether share has stuck more than threshold.

[manila] Handle 'creating' status for non-active replica.

---

scripts/manila-share-sync.py

[manila] sync share size state

---

scripts/manila-share-sync.py

see the individual commit messages

[manila] share sync fixes and logging additions

---

Dockerfile.barbican-nanny
scripts/barbican-db-consistency-and-purge.sh

Ref : https://github.com/sapcc/helm-charts/pull/5068

[Barbican] Introduce barbican nanny

---

nannies/manila-missing-snapshot.py

rare inconsistency, but we have observed it

[manila] missing-snapshot: catch NotFound on GET share_instance

---

scripts/manila-check-affinity.py
scripts/manila-share-snapshot.py
scripts/manilananny.py

see the individual commit messages

[manila] snap reauth

---

scripts/manila-quota-sync.py
scripts/manilananny.py

[manila] reset reserved quota for shares/snapshots

---

nannies/manila-missing-snapshot.py
scripts/manilananny.py

Fixes https://github.com/sapcc/openstack-nannies/issues/64

manila: Add pagination in list API

---

scripts/manila-db-consistency-and-purge.sh

since we moved out the secrets, the config is spread across multiple
files.
follows eb41b009a360277e42529cebc40e3d61198cbff5

[manila] add config dir to manila manage purge command

---

scripts/manila-share-sync.py

[manila] use harvest metrics
